--Users table to store the user related data
CREATE TABLE IF NOT EXISTS HN_USERS(
    ID SERIAL PRIMARY KEY ,
    USER_HANDLE VARCHAR(200) UNIQUE NOT NULL ,
    HN_AGE INTEGER
);

--HN_STORY table is created to store the Story as per the recommendation
CREATE TABLE IF NOT EXISTS HN_STORY(
	ID INTEGER PRIMARY KEY,
	TITLE VARCHAR(200) NOT NULL,
	URL VARCHAR(200),
	SCORE INTEGER NOT NULL,
	USER_ID INTEGER NOT NULL,
	SUBMISSION_TIME TIMESTAMP NOT NULL
);

ALTER TABLE HN_STORY ADD CONSTRAINT FK_HN_STORY_USER_ID FOREIGN KEY(USER_ID) REFERENCES HN_USERS(ID) ;

--HN_COMMENT table is created to store the Top Comments of the story
CREATE TABLE IF NOT EXISTS HN_COMMENT(
	ID INTEGER PRIMARY KEY,
	COMMENT_TEXT TEXT ,
	STORY_ID INTEGER NOT NULL,
	USER_ID INTEGER NOT NULL,
	COMMENT_TIME TIMESTAMP NOT NULL,
	COMMENT_COUNT INTEGER NOT NULL
);

ALTER TABLE HN_STORY ADD CONSTRAINT FK_HN_COMMENT_USER_ID FOREIGN KEY(USER_ID) REFERENCES HN_USERS(ID) ;
ALTER TABLE HN_COMMENT ADD CONSTRAINT FK_HN_COMMENT_STORY_ID FOREIGN KEY(STORY_ID) REFERENCES HN_STORY(ID) ;

COMMIT;
